### ISSUE TITLE
Image distorted when resized in a non-uniform way (aspect ratio changed)

### ISSUE THREAD

**Issue by WelliSolutions** [s1291/InkRasterPerspective#5]
First of all thanks for this awesome extension. This is exactly what I need.

The following does not happen for all images. I have not yet identified criteria when it happens or when it doesn't.

Using commit https://github.com/s1291/InkRasterPerspective/commit/897d8eb4532eac2032d4dc17f8c30fe4c3b053fe which fixes #4 so I can use linked images.

I start with a linked image like this 1280x960 pixel 24 bit 3.5 MB BMP file:

![image](https://user-images.githubusercontent.com/14279507/202008149-7086a340-45cc-49e6-91b8-ad9b07c53fb8.png)

and I get this result

![image](https://user-images.githubusercontent.com/14279507/202008575-45d01e62-860c-48ae-b4d4-1895c2cf3701.png)

Note the lower right corner which doesn't match the path.

**Comment by WelliSolutions** [comment]
This seems to happen if an image was linked or embedded into Inkscape and after that it is resized in a non-uniform way (i.e. the aspect ratio changed).

**Comment by s1291** [comment]
> This seems to happen if an image was linked into Inkscape and after that it is resized in a non-uniform way (i.e. the aspect ratio changed).

A workaround in this case is to make a bitmap copy of the rescaled image: **Edit** > **Make a Bitmap Copy**. then apply the persperctive transformation on it.

**Comment by WelliSolutions** [comment]
Suggestion for ~ line 153:
```python
        scale = pil_img_size[0] / img_width
        img_height = pil_img_size[1]               # additional line

        coeffs = self.find_coeffs(
```

**Comment by siteleas** [comment]
Here is my original:
![Screenshot from 2023-12-14 13-43-24](https://github.com/s1291/InkRasterPerspective/assets/658069/538e9a2a-6d27-43df-9b64-6c354919ae59)
This is what happens after applying the effect. Please help:
![Screenshot from 2023-12-14 13-47-53](https://github.com/s1291/InkRasterPerspective/assets/658069/d4c6a787-1208-4524-b804-fc35f49c13fb)

**Comment by siteleas** [comment]
This is the XML Editor information:
![Screenshot from 2023-12-14 13-55-04](https://github.com/s1291/InkRasterPerspective/assets/658069/fb299064-9adf-4535-83ae-d72a80736391)

**Comment by s1291** [comment]
@siteleas 
Are you following this node order for you path?
![image](https://github.com/s1291/InkRasterPerspective/assets/17838489/45b8d8fb-7c6c-4a20-9dfc-f20a80f631a2)

**Comment by o5krsil** [comment]
Currently it does not work in Inkscape version 1.4.2

It throws the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\imagePerspective.py", line 25, in <module>
    from PIL import Image as PIL_Image
  File "C:\Program Files\Inkscape\lib\python3.12\site-packages\PIL\Image.py", line 97, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```
